apiVersion: v1
kind: Service
metadata:
  name: claude-code-intelligence-service
  namespace: claude-code-intelligence
  labels:
    app.kubernetes.io/name: claude-code-intelligence
    app.kubernetes.io/instance: claude-code-intelligence
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: claude-code
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: claude-code-intelligence
    app.kubernetes.io/instance: claude-code-intelligence

---
apiVersion: v1
kind: Service
metadata:
  name: claude-ollama-service
  namespace: claude-code-intelligence
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: claude-ollama
    app.kubernetes.io/component: ai-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 11434
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: claude-ollama

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: claude-code-intelligence
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/component: reverse-proxy
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx

---
# Headless service for Prometheus service discovery
apiVersion: v1
kind: Service
metadata:
  name: claude-code-intelligence-headless
  namespace: claude-code-intelligence
  labels:
    app.kubernetes.io/name: claude-code-intelligence
    app.kubernetes.io/instance: claude-code-intelligence
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: claude-code-intelligence
    app.kubernetes.io/instance: claude-code-intelligence